name: Publish

on:
  push:
    tags:
      - "*"
env:
  PROJECT_NAME: "XinjingdailyBot"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os : [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            arch: osx-x64
          - os: windows-latest
            arch: win-x64
          - os: windows-latest
            arch: win-arm
          - os: windows-latest
            arch: win-arm64
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          submodules: recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x

      - name: Verify .NET Core
        run: dotnet --info

      - name: Restore packages in preparation for ${{ env.PROJECT_NAME }} publishing
        run: dotnet restore ${{ env.PROJECT_NAME }} -p:ContinuousIntegrationBuild=true --nologo

      - name: Publish ${{ matrix.os }} ${{ matrix.arch }}
        run: dotnet publish ${{ env.PROJECT_NAME }} --runtime ${{ matrix.arch }} -p:PublishSingleFile=true --self-contained true -o ./tmp/${{ env.PROJECT_NAME }} -c Release

      - name: zip files
        run:  7z a -bd -slp -tzip -mm=Deflate -mx=5 -mfb=150 -mpass=10 "./dist/${{ matrix.arch }}.zip" "./tmp/${{ env.PROJECT_NAME }}"

      - name: Upload ${{ env.PROJECT_NAME }}-${{ matrix.arch }}
        continue-on-error: true
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.arch }}
          path: ./dist/${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Download win-x64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: win-x64
          path: out

      - name: Download win-arm artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: win-arm
          path: out

      - name: Download win-arm64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: win-arm64
          path: out

      - name: Download osx-x64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: osx-x64
          path: out

      - name: Download linux-x64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: linux-x64
          path: out

      - name: Download linux-arm artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: linux-arm
          path: out

      - name: Create ${{ env.PROJECT_NAME }} GitHub release
        id: github_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.PROJECT_NAME }} ${{ github.ref }}
          body: release created bt github actions
          prerelease: true

      - name: Upload win-x64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/win-x64.zip
          asset_name: ${{ env.PROJECT_NAME }}-win-x64.zip
          asset_content_type: application/zip

      - name: Upload win-arm to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/win-arm.zip
          asset_name: ${{ env.PROJECT_NAME }}-win-arm.zip
          asset_content_type: application/zip

      - name: Upload win-arm64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/win-arm64.zip
          asset_name: ${{ env.PROJECT_NAME }}-win-arm64.zip
          asset_content_type: application/zip

      - name: Upload osx-x64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/osx-x64.zip
          asset_name: ${{ env.PROJECT_NAME }}-osx-x64.zip
          asset_content_type: application/zip

      - name: Upload linux-x64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/linux-x64.zip
          asset_name: ${{ env.PROJECT_NAME }}-linux-x64.zip
          asset_content_type: application/zip

      - name: Upload linux-arm to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/linux-arm.zip
          asset_name: ${{ env.PROJECT_NAME }}-linux-arm.zip
          asset_content_type: application/zip
